// Local 

GET http://localhost:3000/contacts

### 
GET http://localhost:3000/contacts/626bb837a5171a37ee89d7fe

### 
GET http://localhost:3000/contacts/626bb837a5171a37ee89d7ff

### 
GET http://localhost:3000/contacts/626bb837a5171a37ee89d800

// Heroku
###
GET https://cse341-heroku-app.herokuapp.com/contacts

### 
GET https://cse341-heroku-app.herokuapp.com/contacts/626bb837a5171a37ee89d7fe

### 
GET https://cse341-heroku-app.herokuapp.com/contacts/626bb837a5171a37ee89d7ff

### 
GET https://cse341-heroku-app.herokuapp.com/contacts/626bb837a5171a37ee89d800