////////////////////////////////////////////////
//// LOCAL TESTING 

GET http://localhost:3000/contacts

### 
GET http://localhost:3000/contacts/626bb837a5171a37ee89d7fe

###
POST http://localhost:3000/contacts HTTP/1.1
content-type:application/json

{
    "firstName": "Austin",
    "lastName": "Rochette",
    "email": "austin@example.com",
    "favoriteColor": "red",
    "birthday": "12/2/96"
}

/////////////////////////////////////////////////
//// HEROKU PUBLISHED
###
GET https://cse341-heroku-app.herokuapp.com/contacts

### 
GET https://cse341-heroku-app.herokuapp.com/contacts/626bb837a5171a37ee89d7fe
